// src/data/caseStudiesData.js
export const caseStudies = [
  {
    id: 1,
    title: "Lumina Brand Identity",
    description: "Rebranding Lumina into a minimal, modern digital-first identity.",
    image: "/images/case-studies/lumina-cover.jpg",
    slug: "lumina",
    category: "Brand Strategy",
  },
  {
    id: 2,
    title: "Aurix Social Media Strategy",
    description: "Boosting engagement through authentic storytelling and design.",
    image: "/images/case-studies/aurix-cover.jpg",
    slug: "aurix",
    category: "Social Media Campaign",
  },
  {
    id: 3,
    title: "BlueOrbit Website Redesign",
    description: "Turning a B2B platform into a design-driven experience.",
    image: "/images/case-studies/blueorbit-cover.jpg",
    slug: "blueorbit",
    category: "UI/UX Design",
  },
  {
    id: 4,
    title: "Verde Visual Language",
    description: "Creating a vibrant color-led visual identity for a green startup.",
    image: "/images/case-studies/verde-cover.jpg",
    slug: "verde",
    category: "Creative Direction",
  },
  {
    id: 5,
    title: "Pulse Product Campaign",
    description: "Building momentum for a new consumer tech product launch.",
    image: "/images/case-studies/pulse-cover.jpg",
    slug: "pulse",
    category: "Marketing & Launch",
  },
  {
    id: 6,
    title: "Natura Brand Ecosystem",
    description: "Designing a cohesive brand system across digital touchpoints.",
    image: "/images/case-studies/natura-cover.jpg",
    slug: "natura",
    category: "Brand Systems",
  },
  {
    id: 7,
    title: "Flow Agency Reel",
    description: "Crafting a cinematic motion showcase to express brand emotion.",
    image: "/images/case-studies/flow-cover.jpg",
    slug: "flow",
    category: "Motion Design",
  },
  {
    id: 8,
    title: "Peak Apparel Campaign",
    description: "Defining visual storytelling for an emerging streetwear brand.",
    image: "/images/case-studies/peak-cover.jpg",
    slug: "peak",
    category: "Creative Campaign",
  },
  {
    id: 9,
    title: "Orbit Growth Report 2025",
    description: "Turning complex data into compelling, visually engaging stories.",
    image: "/images/case-studies/orbit-cover.jpg",
    slug: "orbit",
    category: "Data Storytelling",
  },
];
